### ISSUE TITLE
this require numpy 1.26 will Not compatible with Rembg 、WAS-node-suite-comfyui

### ISSUE THREAD

**Issue by Erwin11** [nosiu/comfyui-instantId-faceswap#11]
this require numpy 1.26 will Not compatible with Rembg 、WAS-node-suite-comfyui.
Rembg 、WAS-node-suite-comfyui. is need numpy 1.25
I had reinstalled require for Rembg.

**Comment by nosiu** [comment]
it works fine with numpy 1.25.0
