### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by Uniky** [nosiu/comfyui-instantId-faceswap#15]
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/24896456/525ee644-3768-485d-9b81-c57adc8bfe7e)

**Comment by Uniky** [comment]
It's weird because I've used the same workflow without an error, but after disconnecting the LCM Lora this error occurred even if I reconnect the Lora the error still exists.

**Comment by Uniky** [comment]
https://github.com/nosiu/comfyui-instantId-faceswap/assets/24896456/cc196f6e-095d-4fcf-a4e1-0f250c99eb9f

It is weird because this error will affect other workflows that use Diffuser as well

**Comment by nosiu** [comment]
If it worked before maybe by mistake you removed your cache or something, by default this model is located somewhere around here (on windows)
C:\Users\YOUR_USER_NAME\.cache\huggingface\hub
maybe you cleared your cache or something

**Comment by Uniky** [comment]
I do have the cache folder which named models--openai--clip-vit-large-patch14, and I even delete it to see if the workflow would regenerate for me, but it seems only the other InstantID workflow regenerated the folder and downloaded the required files automatically.
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/24896456/44b3c26f-ce55-4f5b-83d0-ba49a11467c6)
However, this does not work for your workflow, the error remains.

**Comment by nosiu** [comment]
no longer relevant, since the version update
