### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by sugatasanshiro** [nosiu/comfyui-instantId-faceswap#17]
![chrome_YoUDOdWnso](https://github.com/nosiu/comfyui-instantId-faceswap/assets/143538601/4de7b12b-cbff-4526-9799-7594e8de2922)

**Comment by nosiu** [comment]
It's hard to say without knowing what the console spits out. For my part, I can say that there was a version update today and maybe there is a problem with the cache (?) in the ComfyUI manager (I will check tomorrow if the problem still exists)

I had no idea that someone added this extension there.

In the worst case, the solution would be to download the repository as, for example, ZIP (CODE -> download ZIP).
Unpacking and pasting the files to ComfyUI/custom-nodes/comfyui-instantId-faceswap and overwrite changes.

+ installing new diffusers 0.26.x info in the changelog section in the readme

**Comment by johndpope** [comment]
update.sh - run inside your /comfyui/custom_nodes (every day)

```shell
#!/bin/bash

Green='\033[0;32m'
Def='\033[m'

echo -e "${Green}MainApp:${Def}"
git pull
echo ---

for f in *; do
    if [ -d "$f" ]; then
        echo -e "${Green}$f:${Def}"
        cd "$f"
        git pull
        echo ---
        cd ..
    fi
done

```
