### ISSUE TITLE
Add this auto facemask method

### ISSUE THREAD

**Issue by shivshankar11** [nosiu/comfyui-instantId-faceswap#20]
![Screenshot 2024-02-07 100036](https://github.com/nosiu/comfyui-instantId-faceswap/assets/7979031/1b0cdf04-1346-4a6e-8258-d681ce84f821)

**Comment by shivshankar11** [comment]
btw why not merge diff nodes
![Screenshot 2024-02-07 100327](https://github.com/nosiu/comfyui-instantId-faceswap/assets/7979031/6e6a3239-b296-46d1-9e8e-80aa01bf0157)

**Comment by nosiu** [comment]
you can add it yourself now
