### ISSUE TITLE
Not empty face embedding cache.

### ISSUE THREAD

**Issue by skywalker00001** [nosiu/comfyui-instantId-faceswap#21]
Hi, there. I tried to upload the initial two reference images, and the result is pretty good ( similar to the two ref imgs), but when I tried to change the reference images, the result seems to be the blend of my previous two images and current two ref images. So how to empty face embedding cache so that when I try to change the ref image, I can get the correct result?

**Comment by skywalker00001** [comment]
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/31678783/b1fd2075-2c60-4f8b-b26e-7d121ddbcc99)
You can see the result of wearing glasses, which refers to the previous reference images wearing glasses. But I only want to refer current character.

**Comment by nosiu** [comment]
yep, should be fixed now

**Comment by skywalker00001** [comment]
您好，我是侯翼，您的邮件已收到，祝您生活愉快~
