### ISSUE TITLE
stable-fast now support instantid pipeline

### ISSUE THREAD

**Issue by shivshankar11** [nosiu/comfyui-instantId-faceswap#23]
stable-fast is able to optimize InstantID pipeline and achieves a 1.8x speedup! 
https://github.com/chengzeyi/stable-fast/blob/main/examples/optimize_instant_id_pipeline.py

**Comment by nosiu** [comment]
Yea saw that, I just don't see any gain here. They said there is a warm-up stage at the beginning so the first iteration takes longer and with LCM Lora you are generating quality pictures in 1 -2 steps.
Does anyone have any convincing arguments?

**Comment by shivshankar11** [comment]
If adding support for stable fast is not impacting anything in negative way then should include it, 1.8x speed is lot to be left on table if someone is video faceswaping.
Btw can pipeline support unet and vae as input instead of checkpoint?
