### ISSUE TITLE
Black space where face should be

### ISSUE THREAD

**Issue by pr1ntr** [nosiu/comfyui-instantId-faceswap#25]
So this is what I get. I remember having this issue with automaticwebui something to do with xformers.. i don't remember now though. Any ideas?

![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/1272089/f52f25df-1040-4944-8a18-146f713a36c9)

**Comment by pr1ntr** [comment]
if i set --fp32-vae then i get this 
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/1272089/5635eb5c-9b84-47d5-a9c6-fcb2adf1cacc)

**Comment by nosiu** [comment]
**It hasn't been tested with turbo models**
You are using LCM Lora and turbo model which is a very bad combo.
Also, you are resizing the face to 1024px, so it will try to generate something quite big 1024x~512 (guessing based on the aspect ratio of the mask), and turbo models usually can generate images no larger than 512x512

**Comment by anyshu** [comment]
same issue. black mask cannot be removed.

**Comment by claireliu14** [comment]
I got same problem ..
My comfyui is a version that supports CUDA121, but when executing instantid-faceswap, it will ask to use cuda 11, so I tried to install cuda 11.8 toolkit, but not used (If I change to cuda 11.8, comfyui while get error in ksampler). Could it be related to this?
![Screenshot 2024-02-21 at 11 06 34 AM](https://github.com/nosiu/comfyui-instantId-faceswap/assets/6873073/11d23ee5-7253-4785-b35e-5a092b2b655e)

**Comment by nosiu** [comment]
@claireliu14 try to run comfy with `--fp32-vae` argument, Console should say
```
VAE dtype: torch.float32
```

**Comment by deepfree2023** [comment]
Tested several models, all  normal models without lcm,turbo, dpo, etc., some worked well, some only produced black mask. Don't know why...

**Comment by matabear-wyx** [comment]
> Tested several models, all normal models without lcm,turbo, dpo, etc., some worked well, some only produced black mask in the final result but the preview image was correct. Don't know why... with lcm lora enabled or not didn't affect the result.

Could u please share the models that worked well?

**Comment by deepfree2023** [comment]
> > Tested several models, all normal models without lcm,turbo, dpo, etc., some worked well, some only produced black mask in the final result but the preview image was correct. Don't know why... with lcm lora enabled or not didn't affect the result.
> 
> @deepfree2023 Could u please share the models that worked well?

Sure, realvisXLV40, animaPencilXL_v150, albedoBaseXL_v21, dynavisionXL

**Comment by liyunfei54** [comment]
> > > 测试了几个型号，都是没有lcm、turbo、dpo等的普通型号，有些效果很好，有些在最终结果中只产生了黑色蒙版，但预览图像是正确的。不知道为什么...... lcm lora 启用与否并没有影响结果。
> > 
> > 
> > @deepfree2023您能分享一下效果很好的模型吗？
> 
> 当然，realvisXLV40、animaPencilXL_v150、albedoBaseXL_v21、dynavisionXL

thanks

**Comment by longmans** [comment]
It seems not stable, it crashs sometimes.

**Comment by nosiu** [comment]
no longer relevant, since the version update
