### ISSUE TITLE
face shape mismatch problem

### ISSUE THREAD

**Issue by deepfree2023** [nosiu/comfyui-instantId-faceswap#26]
![ComfyUI_temp_ghqta_00002_](https://github.com/nosiu/comfyui-instantId-faceswap/assets/158825912/240fc443-88d3-4d2c-bc29-346f39a0b47e)
I've got lots of face shape mismactch results like this one, using the example workflows. Is there any reason or solution to this problem?

**Comment by nosiu** [comment]
not enough mask is drawn around the face / too much mask blur

**Comment by deepfree2023** [comment]
Thank for the tips. Seems much better now.
