### ISSUE TITLE
Suggestion. Add a mask for face swap that is not the same as for the face detection.

### ISSUE THREAD

**Issue by zewolf5** [nosiu/comfyui-instantId-faceswap#27]
For a better end result, using any of the ComfyUI tools to get a mask with only the face will be better than a square box for the face swap part.
So I tested this and works like charm. Just allow for a second mask into the "Faceswap generate" to be used for the actual faceswap. That face swap mask is too small to be used for face detection and almost always fail.

Or add a Dilation field to increase the area around the one mask being used.

![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/2631513/dea85d0c-4e32-47d9-83a7-7e158db5f0a0)
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/2631513/97ccf725-ccfb-4574-8318-8fcf330400ac)
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/2631513/e49f2984-4545-442d-b561-d33ba60c7fa6)

**Comment by zewolf5** [comment]
Ignore this. Padding = Dilation it seems.

So just close it.

**Comment by nosiu** [comment]
this might be a good idea for an attention mask for control net

**Comment by nosiu** [comment]
no longer relevant, since the version update
