### ISSUE TITLE
stuck at Load EVERYTHING node

### ISSUE THREAD

**Issue by zodiacg** [nosiu/comfyui-instantId-faceswap#30]
Use SDXL official base checkpoint. Log shows bunch of "Applied Providers" and stopped at "set det-size: (640, 640). Then everything stuck here can the queue can't be cancelled. I have to restart ComfyUI altogether to move on.

From the gpu consumption I assume the model is not yet loading.

**Comment by nosiu** [comment]
no longer relevant since the version update
