### ISSUE TITLE
Updated the comfyui ontology, ran this plugin, but encountered an issue

### ISSUE THREAD

**Issue by tanglup** [nosiu/comfyui-instantId-faceswap#32]
执行FaceSwapGenerationInpaint时出错：
StableDiffusionXLControlNetInpaintPipeline.prepare_control_image（）获得了意外的关键字参数“crops_coords”
See where the problem lies

**Comment by nosiu** [comment]
update diffusers to 0.26.x version.
There is instruction in the readme on how to do it

**Comment by tanglup** [comment]
> 将扩散器更新到 0.26.x 版本。 自述文件中有关于如何操作的说明

It's probably clear, okay, thanks
