### ISSUE TITLE
Face Embed Stacker

### ISSUE THREAD

**Issue by skyler14** [nosiu/comfyui-instantId-faceswap#35]
Have you considered making a stacker variant of your face embed, or just a node that accepts a stack of images and outputs the face embeds? This is almost already hackable from group nodes on your face embed, but we dont need to feed multiple insightface or face embeds, so at that point it's just a matter of accepting n images.

**Comment by nosiu** [comment]
Yes, I have considered it.
I decided it would be too expensive considering the time I would spend writing the UI.
At first glance, it seems simple, but if you think about UX, the fact is that such added images need to be edited (removed).
Provide an option to somehow mark facial images where face can't be found (they can't just be skipped), even if they seem OK at first glance, etc.

All this seems to be at odds with the authors' vision of a comfy, "the way of spaghetti hell".

If someone is bothered by inserting and connecting all the nodes just use the script to generate the workflow, that's what it was created for.

**Comment by skyler14** [comment]
Fair fair. Any chance you might be able to give me a bit more of an outline of your mega nodes process so I can see about porting the functionality as closely as possible to the native instantid implementation? I was under the impression inpainting generally requires an inpainting model to not generally make a mess but you see be doing quite well to get around that requirement with what you do here. With that I can use some of the standard image stacking methods since it accepts batches of images just as easily.
