### ISSUE TITLE
Error occurred when executing FaceSwapGenerationInpaint:  zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by zmwv823** [nosiu/comfyui-instantId-faceswap#38]
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/13308350/acdeace2-2c3b-41b2-832b-21a1ccfd9608)

**Comment by Tanglinling** [comment]
How was the problem solved?

**Comment by zmwv823** [comment]
> How was the problem solved?

By delete this custom-node and use reactor.

**Comment by nosiu** [comment]
> How was the problem solved?

Many times by many people.
https://github.com/nosiu/comfyui-instantId-faceswap/issues/47
https://github.com/nosiu/comfyui-instantId-faceswap/issues/34

It would be best to draw a mask so the model would know what face to replace.
