### ISSUE TITLE
Face Embed sometimes not detecting face when the original InstantID repo will detect that  same face.

### ISSUE THREAD

**Issue by Starzilla29** [nosiu/comfyui-instantId-faceswap#39]
![ComfyUI_temp_ljjfq_00001_](https://github.com/nosiu/comfyui-instantId-faceswap/assets/47699576/fb39bff4-25a2-431b-81ce-002ee1d7b831)

![ComfyUI_temp_ycicd_00001_](https://github.com/nosiu/comfyui-instantId-faceswap/assets/47699576/7f5384e8-3b05-42b4-97ab-b3d700eed471)

As a sort of training exercise I have trained the above faces with stable diffusion and tried face swapping them. I have been using this face swapper on normal images, and it has recognized the faces each time, so when it happened with these ones I thought.... maybe these did look enough like a real face to work? but they look pretty good, so I tried it with vanilla InstantID and the faces were recognized immediately with no problem.

I have had issues with it recognizing the face before if there wasn't enough padding, or if my mask was too small. I feel I am familiar enough with these issues to work through it if there is a problem, but no amount of padding, or increasing the mask solves the issue, I even painted the mask over the entire image and it still didn't work (and this worked with my real photos that I was doing). It should be noted that this also happens when plugging these images into the face embed node. To me, this screams there is something different happening here. Why can't the faceswap node suite recognize the images when insight face nodes from InstantID can no problem?

**Comment by nosiu** [comment]
(hopefully) no longer relevant, since the version update
