### ISSUE TITLE
StableDiffusionXLControlNetInpaintPipeline.prepare_control_image() missing 2 required positional arguments: 'crops_coords' and 'resize_mode'

### ISSUE THREAD

**Issue by steak3** [nosiu/comfyui-instantId-faceswap#4]
First of all, thank you for this amazing work.

![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/14215758/85ddfc33-23de-4a79-8033-7dcdce928d0b)

I have this error with no clue why.
ComfyUI with last update as well as extensions.
JuggernautXL checkpoint
Diffusers version 0.26.0

**Comment by steak3** [comment]
Downgraded to 0.25.1 with conflicts and some manual dependency install, but it worked at the end 👍
Supporting 0.26.0 could be nice in the future (it's very recent, from Jan-31)

**Comment by nosiu** [comment]
Dependency hell. The worst thing is that the code fully supported what seems to be 0.26.0 now.
I based everything on what was on their dev branch and manually changed what didn't work. 
Lesson learned.

**Comment by 362658555** [comment]
You can try the installation step mentioned by the author: 'Open the command line in the ComfyUI/custom_nodes/comfyui-instantId-faceswap/ folder and type pip install -r requirements.txt to install dependencies.' I resolved the same issue this way.

**Comment by nosiu** [comment]
no longer relevant, since the version update
