### ISSUE TITLE
Why is there a blurred boundary around the edges of the face after a face swap?

### ISSUE THREAD

**Issue by 21Timothy** [nosiu/comfyui-instantId-faceswap#41]
<img width="341" alt="企业微信截图_9a1613f8-391f-4f2a-b37f-f45c4d044316" src="https://github.com/nosiu/comfyui-instantId-faceswap/assets/38107672/9d253170-95a0-4f3e-bddc-d7665b655d53">

Here's the params. ASK for help!

**Comment by nosiu** [comment]
no longer relevant, since the version update
