### ISSUE TITLE
Face not getting replaced

### ISSUE THREAD

**Issue by tp-x2y2** [nosiu/comfyui-instantId-faceswap#49]
Here's my log
```
Prompt executed in 0.03 seconds
got prompt
/home/x/anaconda3/envs/comfy/lib/python3.9/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.53it/s]
/home/x/anaconda3/envs/comfy/lib/python3.9/site-packages/diffusers/image_processor.py:90: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
Prompt executed in 9.75 seconds
```

And here's the result:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/d7c68e89-4877-47fc-be71-2bdfec538b0f">

Any help will be appreciated!

**Comment by nosiu** [comment]
check your diffusers version command: `pip show diffusers`

**Comment by tp-x2y2** [comment]
Thank you! Here's the output.

```
Name: diffusers
Version: 0.26.3
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: patrick@huggingface.co
License: Apache 2.0 License
Location: /home/jyo/anaconda3/envs/comfy/lib/python3.9/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by: 
```

**Comment by nosiu** [comment]
version is fine, I just noticed it took 00:00:00 seconds to generate, are you on windows using an NVIDIA card with CUDA?

**Comment by tp-x2y2** [comment]
Yes. I'm using WSL with a 4080 card.

**Comment by tp-x2y2** [comment]
In my first post, the `Prompt executed in 0.03 seconds` log came from a previous execution which I had a redo with a fixed seed. The job actually took 9.75 seconds.

Do you think I could get a different result using windows directly? And I've tried several other SDXL checkpoints, which gave me almost same results.

**Comment by nosiu** [comment]
This part is important in your case
`100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.53it/s]`

The total time at the end (0.03 seconds or 9.75) is just moving models around in the memory and decoding.
So it looks more like this in the "normal" case;
![image](https://github.com/user-attachments/assets/5d2008dd-2647-46cb-a9f1-ecc38719dad8)

**Comment by tp-x2y2** [comment]
Thanks for the reply. I'll dig around and will let you know if I get any progress.

**Comment by tp-x2y2** [comment]
I finally had it working by using `RealVisXL_V4.0.safetensors`

**Comment by tp-x2y2** [comment]
Any advice on selecting checkpoints? If no, I'll close this issue.

**Comment by nosiu** [comment]
No advice, since it's not a real standard it's random.

**Comment by tp-x2y2** [comment]
Thank you!
