### ISSUE TITLE
Help me with TORCH_CUDA_ARCH_LIST

### ISSUE THREAD

**Issue by XKMEXX** [nosiu/comfyui-instantId-faceswap#51]
Warn!: F:\AI\COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

**Comment by nosiu** [comment]
(hopefully) no longer relevant since the version update
