### ISSUE TITLE
No face detected in pose image.. I would appreciate any help 

### ISSUE THREAD

**Issue by anseltrust** [nosiu/comfyui-instantId-faceswap#52]
![image](https://github.com/user-attachments/assets/0c8e312d-0329-4805-bab8-4f2b6c19ec33) I uninstalled and installed insightface twice, also the custom node but nothing fixed yet, I would appreciate any help 
![image](https://github.com/user-attachments/assets/8b8f2216-9b06-4234-a79d-8dca7a41c10d)
![image](https://github.com/user-attachments/assets/417c48eb-1517-489e-b6de-df66f1d06529)

**Comment by nosiu** [comment]
no longer relevant, since the version update

**Comment by abhinavzspace** [comment]
I am still getting this error:
```
!!! Exception during processing !!! No face detected in pose image
Traceback (most recent call last):
  File "/home/abhi-ubuntu/projects/comfyui/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/abhi-ubuntu/projects/comfyui/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/abhi-ubuntu/projects/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/abhi-ubuntu/projects/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/abhi-ubuntu/projects/comfyui/custom_nodes/comfyui-instantId-faceswap/nodes.py", line 476, in preprocess_image_simple
    return self.preprocess_image(
  File "/home/abhi-ubuntu/projects/comfyui/custom_nodes/comfyui-instantId-faceswap/nodes.py", line 410, in preprocess_image
    kps = get_kps_from_image(image, insightface) if insightface else None
  File "/home/abhi-ubuntu/projects/comfyui/custom_nodes/comfyui-instantId-faceswap/utils.py", line 100, in get_kps_from_image
    assert len(face_info) > 0, "No face detected in pose image"
AssertionError: No face detected in pose image
```

**Comment by nosiu** [comment]
Insightface cannot detect a face in the masked area (+ padding), you might be able to detect a face with your own eyes but insightface just can't.
I cannot do anything about that. just draw your own KPS (those color points) there is workflow for that (draw_kps.json) with an example picture showing how to do it.

![image](https://github.com/user-attachments/assets/4eaceaa3-4f9a-4c65-b56e-6ee962e8488b)

**Comment by abhinavzspace** [comment]
We are actually using 3 images as input for insightface. We have a workflow in which we keep changing the "target" image in which faceswap happens, but these 3 images as input remain same.

Strangely it works fine for some target images and while fails on others with the mentioned error. 

The error I was getting for "Insightface cannot detect a face in the masked area (+ padding)" was related to [this issue](https://github.com/nosiu/comfyui-instantId-faceswap/issues/22).

Kindly let me know if you need more information.

**Comment by abhinavzspace** [comment]
You are right. Thanks @nosiu
