### ISSUE TITLE
FaceSwapGenerationInpaint zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by Tanglinling** [nosiu/comfyui-instantId-faceswap#53]
![{4D7A9722-0C56-44B9-A504-0BE7ACA9B36A}](https://github.com/user-attachments/assets/5182cf0c-d121-4e94-84f4-1700870f98fe)

**Comment by nosiu** [comment]
https://github.com/nosiu/comfyui-instantId-faceswap/issues/47
https://github.com/nosiu/comfyui-instantId-faceswap/issues/34

**Comment by nosiu** [comment]
no longer relevant, since the version update
