### ISSUE TITLE
draw kps node does not accept standard image input

### ISSUE THREAD

**Issue by yegods** [nosiu/comfyui-instantId-faceswap#55]
I'm trying to use the Draw KPS node with an input reference image that doesn't originate from the standard Load Image comfy node.  This does not function correctly.  The image gets loaded as I can see in the preview, but it doesn't get applied to the kps editor, nor the Draw KPS preview.  The reference image while in the kps editor shows up as blank, so it's pretty useless.

I've looked around the code, and see that the Draw KPS node is pulling the reference image directly from the Load Image node internals (in the file modal.js, probably the app.registerExtension function).  Not sure why, and I don't have the know-how to change and/or fix, or I would.

If this is not understandable, and you need a workflow, let me know.  I definitely like the functionality of this node, but need it to work with any arbitrary input image, since I don't use the Load Image node much.

as a side note, i did try and modify the Load Image node to work with an input image path, but that was also only partially successful, and the "internal" image was not updated to the new image, but was only updated to the image selected from the list as normal, but the output image was the correctly loaded image from the path.  Sorry for the rambling... I've been bashing my head against this for a while now.  Hopefully, it is an easy fix.

**Comment by nosiu** [comment]
Sorry but I don't think I get it. Could you provide a workflow or screenshot of what you mean? But keep in mind it must use only internal comfy nodes because I don't want to support third-party nodes.

**Comment by yegods** [comment]
sure, i will get a workflow together that doesn't use my modified Load Image node, and put it up here.

**Comment by yegods** [comment]
[instantid enhance example.json](https://github.com/user-attachments/files/17560385/instantid.enhance.example.json)
example workflow of problem

**Comment by nosiu** [comment]
Your example is using custom nodes (extensions) I need something that will work with normal comfy, no plugins/extensions/modifications.

So I prepared other example, hopefully this is what you mean:
![image](https://github.com/user-attachments/assets/75f2e922-b476-4777-a9fb-71c0fe49c503)
[idk.json](https://github.com/user-attachments/files/17560834/idk.json)

Now how to switch fast between image list or your one image from the list?
Right click on the any preview image -> Copy (Clipspace) then
Right click on the load image -> Paste (Clipspace).

You can't just do some operation on the image (loading multiple images and plucking one from the list is also an operation) and then draw KPS. It must done before you query prompts. If you want to use cached images (previous outputs) then just use the Copy/Paste strategy.
I don't have access to python variables from the javascript.

**Comment by yegods** [comment]
ok, well it sounds like you can't do what I wanted, so I will close this.  thanks for looking.
