### ISSUE TITLE
Missing Node Types: PreprocessingImage

### ISSUE THREAD

**Issue by GEArce** [nosiu/comfyui-instantId-faceswap#56]
Any fix for this?

![Captura](https://github.com/user-attachments/assets/7a5f4df1-29a9-492d-9615-68199e53fe83)

I don't have any node called "ComfyUI_rotate_image"

**Comment by nosiu** [comment]
what's the problem? You installed it probably already restarted the comfy and everything should work.

**Comment by nosiu** [comment]
not enough data
