### ISSUE TITLE
What are the vram requirements?

### ISSUE THREAD

**Issue by GaleBoro** [nosiu/comfyui-instantId-faceswap#7]
I'm getting oom error with 8gigs. Could it be possible to reduce vram requirements by making model loading modular?
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/143328685/37f3bbbc-95a2-45d4-bcef-d0e1544e2d66)

**Comment by nosiu** [comment]
should be the same as SDXL so ~8GB VRAM.
I don't think modular loading would help.

**Comment by nDman** [comment]
Needs more than 8gb, InstantID works based on diffusers models, it converts sdxl safetensor files into diffusers format. even on 12gb graphic card I get out of memory errors sometimes. Someone should make it to work without diffusers.

**Comment by hortom** [comment]
I am sure that a similar semi solution can be used here as I added to this PR: https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/87
If the users won't switch on/off multiple optimisations just use one it will be stable enough with 12 GB.

**Comment by nosiu** [comment]
no longer relevant, since the version update
